[alias]
# Platform-specific build aliases
build-windows = "build --package shadowfs-cli --target x86_64-pc-windows-msvc"
build-macos = "build --package shadowfs-cli --target x86_64-apple-darwin"
build-linux = "build --package shadowfs-cli --target x86_64-unknown-linux-gnu"

# Test aliases
test-all = "test --workspace --all-features"
test-core = "test --package shadowfs-core"

# Check aliases
check-all = "check --workspace --all-features"
clippy-all = "clippy --workspace --all-features -- -D warnings"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-apple-darwin]
rustflags = ["-C", "link-arg=-framework", "-C", "link-arg=CoreFoundation"]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "link-arg=-lfuse3"]

[profile.dev]
opt-level = 0
debug = true
incremental = true

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
strip = true

[profile.bench]
inherits = "release"
debug = true